version: "3"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: mypassword
    ports:
      - 5437:5432
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
